# Generated by Django 3.0.3 on 2020-02-09 13:00

from django.db import migrations, models
import django.db.models.deletion
import social.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[(None, 'Select Provider'), ('google', 'Google'), ('github', 'Github'), ('sentinel', 'sentinel')], max_length=10, unique=True)),
                ('client_id', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Social Provider',
                'verbose_name_plural': 'Social Providers',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_provider_identifier', models.CharField(max_length=1000)),
                ('is_connected', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=1000, null=True, unique=True)),
                ('provider', models.ForeignKey(on_delete=models.SET(social.models.get_sentinel_social_provider), to='social.SocialProvider')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
            },
        ),
    ]
